language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    - secure: IotNuSAz/bFo5GyPCM2mxmvH3YbSdADZYgHFstqbcIKKd3QKp+ym5Gq8dURLWL5Lbv9oeJfXRQemuhoHuwW/0auqRSbm/0JORjn6b0CgAyQH4GA5+6TG+8VeXLgIMPZFxs6heNkRThZLKsG30Dz5rCmAqrX5tiRBX/tq+75RNN2WOvygNiVvPn2T4q46Dyrw3uhLUZES/fmUNDmjDHju9ycLhlL7b9VxjU4tp01WgaV69YpbYN3YhoEe5qgKscDuTTZp7WtOd30PxkZXq9n7PWv5AzqqTz2a2QgHYFn3qE1MsPRT8RRrebfQfxogYlLhkawYkInHO7wVSjA8R8cRFii85qJWWf9fehFH28KB8cmazNRBtUSFqPaDPHTqVHANVY7ykaRxx1HwlpWUpas4U60PfMwQDA37qGo4aJkSUoyFj6Zet7rpUkvQaVUkJBWTftzK2KJFp1WPIrW+hZxr9NT6Q2utp/s2SoEXw/0YH5tJa9yP5vUz6Oo717VYftvIpzm89Wc+8+d+Px4KVKoWFX53VTHdLH9Kp118RCy0NdiBHqrcaOy4BIo534BdvKFa5Zl2wTd65BsbKQsbIbFgxVHXFpnxmJE70NOSnLKcgFSRLy+glH2kaqIWRvFQj3dR3/wOfZcXS3uwOHaeup7SDCkfS96Df5ueJbgEmgYSuG8=
    - secure: ZIx/wMZIC6vbaW51NwXz/cmcjQL90NZ2cisKaAynHQ14JZQQ2RhHMH2AE5AOHn8rl/hNSselJtLZ52SOA7EklcZy6xch5KOE+t8k21bkDDXYna29WA3Vrih/GqRjy3AehL/ohDSbOF3olDpc99liegmRP3N/LqP2wkNsQXJ8LNNy7h4n5bJ3dJghjrzfEM6Asm0PitBGkslSndZ0E+begi7QvI6/B0/Lno/JGKKAzcDz3NYalLDkKegAKsoW/Dv3vDuTbsfMl6tiDj+ZSRpvu+xb5/1PjQtfdioXXiZI0W3zpNm97nUcmY+SOaUiwof5l1Y+cgG0ch9OOrz8GHSp8W81CPwHwH/jFtmOaaZ3u+mGndVhfZxkQD1OC0vU8N3YztXJpTLWe3hXwK1UNbiggiphsVz89IfyYDgoMDQRhk/kG/CS0GEyTNGRjoxYGEmr8BIaXEVLTeHphPMK0oyChLJt4oyH6Ka8WgB+X+lIInAVAPa4bCoIIZoHD1ozgE3y7Vclqx29Ka5oOoadQ9j+p7rP8mF9FUF6Fe67G0+7KUOUVA3kXlvlJODtgK9SCq5YtoruBc/ncyGpFFg2A4vGVbSm6KHBtr9NqQ1lpJmN9ijwgqrE9IN6cx0OwOwA+QLFwsIIwlvEE6q5ZKJd5knVG2Qhzrbf6KP/PNrk1bxxhu8=
    - secure: QWSdF5niWV1SjzN6IoPPFW28m8DsPBu809GJGFdTXmC8iCiWvkA3Oq6OAvpAhJYrQ78MhdQdm9VPM58jFwMKT+qqr5l+Ap5h8LkMr2WYxo/qlqnvE9KAHgV/MN3OxfI1v/dNRaSgOIso+eda69OHFHnSYQ5inr9w+oBJ9mdsRgGSx7r71RFpSicBX+ZtsQj/XnX02vwFmiiW3uZMc+6s7zxq0ooSgNcfoyeIfzDOdHSscTqMabN6c0UR3WHITO23irkKmtzXRdr4fuWkgeOxX8jgGLt1Yjboc9oqRKpfOs2fb4Xw5Cy1IvPICD51gm2OfWn49DzIXpVm7CNRwZAvuTyXI8GhjaIJj24w2lpYLnG/oaNcv41hQD+Rjfrtcu3gjsQ2aCGEG9yU5j4T9v2c4//q7XnfDT0+4p4CTDjnq0SsglqQQZ85cc8pBpDAkNU70V1wN8wyCCAXEkacWaWo9GGE07ncMCtRpuCnWs+qM6PiGW+G6HInossf6MQLVkYjyPe6+kuE9eXN8p84Vs1Hho9BeVQsqEmXuGtfpGysXDMk/OzwNiDZA4aefQlIsMcaBeDqZpesvYqsgZUd0z9re1zpicK49zJn8L10JXHuWqDOv6zeC8NiukX39HXGkPptLmHIDO3pM3uv7zqePcg/Ky+kOiwqCHQ3RFg7Cegzgso=
    - secure: LlC2yZFL8K6gprM+UV6GVjIV6Ghit6idQO+bvQg1xpnZ2UdL9toU2tnLM1tjkwDr1nP2rzbkiqK8Z4WDsKO/S1vh3vW0YXpTNkM18JoCBMAu3yUhTcxmL6TYhxD49/zI7tL5oPievq5/KuSl7jWo6f2/Wkp756W1jgq3t28ERfeU4Fa4Rzj3ClE213iWbIbn0J0bNLnzKpAfZIVCCBZ4zJ+Nbq7uJF+onXZ5WYKja4vn035jhuf8oahuqOO4ltjPwIJgkrTDTxd+gxfv6kRo9BdyJuPjvlLUj558ZhmsVNvpiQxAm4FdFzMcQc+AwuGfZaRYRIMk2ICAcPIR4D895EtUnoLBlGvfxy0LBvjk1z5ZOHQpbXQ64Xxv5TZMVnqYUhEiBbCShTrBS1lR3+ITLms6Pt7RxP8szEhWxjLdi5egprEab/ZW2IvEoyNGxrc9V8GGFXv3sQklzJ9kOWNVWOl6w4J2O9Xmskq6S8Ruu7r167mDGHDVwTtNw4iW0AxsS4rOAM8/h8Ryym6p++i76CHhBEZ6LcVJgZRxaspimPjzkoLDsHiCKPJo3WyaZ0+xNxOlqgKJIa4dSJ9AZ9anqyJs9kt7uELgsM6dUzE32J97WUUq7jYoLvay6MZxA9nlaPbgfSMcfauSMk5fU+RKhHCSEUdG9tG6GmLSxNfVFCI=
    - secure: NO6hqdfulnCjw16XbswI8gBY05qTtHXI75md9BvimNBMdPtfzB1MGiMgUAS6zTmddL/5oLaW2gTUAHzDcdSG1+yaIjPwmrt8LFsVxJJ8enVSd/ulmKwEid/boeFdHnID7Mma2urSrPFVyrTwGVicqi52YwoNdrx9K4uebQggmdT/GnKvZir8tjob3mXdfOHUZ1Yk+IzHG928UphNyRyS6wt7Z+5m9F0SIXY15af7XOGhm02ybIYgurSaBA4GERwxLfusrQ2nOZBNb9SN6US5lHHGoclZYm70sb6MOXnlO/TY9mk1mrz57bAfsXEBkGeKCDqewuG7nBA3aTrLJ3nCH+G1xbjESToFfIq5vMnqvJmqxDiBAjsOzNsWzdKNbygrSXQBu4tQL7MVZ0TO0cHdrP4MNMja/EWyEjJP3Pw884bHsuFygZK8fIlMAFT7u5qDw+Ne2P0wIP51IGIBnDGSTSfE41maMzZtliap7LF9w6lIHW7kl/wrAXBx+uZg+lg5ztkogMkgikdFz6zd6/19gGuFKS2NIxqXwwM0HtRSNQj+5BqR18yw+Qh/WPVgBE3BwVyD79gBy6gT/5L7lVJWWynwdtofnZQHjXcae6tiFGgvLPUjthN+2vS12aa9QgooGXh0ASi864nD42auzAt9DK2r76WJI2ZsfZBJSlK2rnw=
addons:
  ssh_known_hosts:
    - ec2-18-184-55-40.eu-central-1.compute.amazonaws.com
    - ec2-3-120-98-15.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=zuulserver-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-18-184-55-40.eu-central-1.compute.amazonaws.com 'bash launch_build.sh'
  on:
    branch: master
