version: "3.9"
services:
  zuulserver:
    container_name: zuulserver
    image: ngomalalibo/zuulserver
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "5555:5555"
    environment:
      MONGODB_DATABASE_STOCKS_ATLAS: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_URI: "http://18.156.118.22:8761/eureka/"
      AUTH_URI: "http://3.121.40.225:8901/user"
      CONF_URI: "http://3.121.40.225:8888"
      DATABASE_URI: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ZIPKIN_URI: "http://18.156.118.22:9411"
      ZUUL_URI: "http://18.184.55.40:5555"
      BOOTSTRAP_SERVERS_CONFIG: "3.120.98.15:9092"
